apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
spec:
  containers:
    - image: mysql:5.5
      name: database
      env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value: password
        - name: MYSQL_DATABASE
          value: invoicePlane
        - name: MYSQL_USER
          value: invoicePlane
        - name: MYSQL_PASSWORD
          value: password
      ports:
        - containerPort: 3306
          name: database
      volumeMounts:
          # name must match the volume name below
        - name: mysql-persistent-storage
          # mount path within the container
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      gcePersistentDisk:
        # This GCE PD must already exist.
        pdName: mysql-disk
        fsType: ext4
